KAB-1011 add infrastructure for integration tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,7 +35,7 @@ jobs:
       # Runs tests with coverage and generates coverage.xml file and test-results.xml file
       # and checks flake8 code-style formatting that is compatible with isort & black
       # see setup in pyproject.toml
-      - name: Run tox
+      - name: Unit tests and code style check
         run: |
           tox
 
@@ -53,6 +53,22 @@ jobs:
           file: ./coverage.xml
           fail_ci_if_error: true
           token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Integration tests
+        env:
+          INTEGTEST_STORAGE_TOKEN: ${{ secrets.INTEGTEST_STORAGE_TOKEN }}
+          INTEGTEST_STORAGE_API_URL: ${{ env.INTEGTEST_STORAGE_API_URL }}
+          INTEGTEST_WORKSPACE_SCHEMA: ${{ env.INTEGTEST_WORKSPACE_SCHEMA }}
+        run: |
+          tox -e integtests
+
+      - name: Publish integration test results
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if a previous step failed
+        with:
+          name: Integration test results (${{ matrix.python-version }})
+          path: ./integtest-results.xml
+          reporter: 'java-junit'
 
       - name: Build wheels package
         run: |
